version: '3'
services:
  beautyx-center:
    stdin_open: true
    tty: true
    container_name: beautyx-center
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules