export const QR_KEY = {
  DISCOUNT_PAGE: 'DISCOUNT_PAGE',
  DISCOUNT: 'DISCOUNT',
  DISCOUNT_CODE: 'DISCOUNT_CODE',
  BANNER: 'BANNER',
  PROMOTION: 'PROMOTION',
  COMMUNITY: 'COMMUNITY',
  CUSTOMER: 'CUSTOMER',
  TIP_PAGE: 'TIPS_PAGE',
  SERVICE_BY_ID: 'SERVICE_BY_ID',
  PRODUCT_BY_ID: 'PRODUCT_BY_ID',
  ORDER_ORG: 'ORDER_ORG',
  Statistic: 'Statistic',
  Organization: 'Organization',
  Productable: 'Productable',
  BrandApps: 'BrandApps',
  BrandAppVersions:'BrandAppVersions',
  GmupTag:'GmupTag',
  GmupTagId:'GmupTagId',
  Trend:'Trend',
  TrendId:'TrendId',
  Comments:'Comments',
}
export const QR_CACHE = 15 * (60 * 1000)
